---
- name: for all servers
  hosts: all
  roles:
    - gitlab
    - issServer

- name: gitlab server
  hosts: GitLab_server
  roles:
    - gitlab

- name: iss Servers
  hosts: issServers
  roles:
    - issServer
