FROM ubuntu:21.10

RUN apt update && apt install -y openssh-server

RUN mkdir /var/run/sshd

EXPOSE 22

RUN echo 'root:ansible%(@' | chpasswd

RUN sed -ri 's/^#?PerminRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config 

RUN apt clean

CMD ["/usr/sbin/sshd", "-D"]

